### ISSUE TITLE
Link images to direct URL to make them expandable.

### ISSUE THREAD

**Issue by royalgraphx** [royalgraphx/DarwinKVM#10]
Currently, some of the images are difficult to read or look at, because they are not able to be expanded. To mitigate this issue, we can simply link each image to their direct link on Github Raw View. An example is as follows:

```html
<p align="center">
  <img src="../../showcase/Helio1421.png">
</p>
```

```html
<a href="https://raw.githubusercontent.com/royalgraphx/DarwinKVM/main/docs/showcase/Helio1421.png"><img src="../../showcase/Helio1421.png" alt=""></a>
```

Issue mainly comes down to not enough free time to do this to all pages, and all images that are not headers.

**Comment by tinphoil** [comment]
I ran `find . -wholename './*.png'` at root to create this list. Do all of these get the above reformatting?

<details>
    <summary>.png files</summary>


./docs/android-chrome-192x192.png
./docs/apple-touch-icon.png
./docs/_site/android-chrome-192x192.png
./docs/_site/apple-touch-icon.png
./docs/_site/android-chrome-512x512.png
./docs/_site/showcase/OpenCoreSonomaInstallationComplete.png
./docs/_site/showcase/HacProKVM140.png
./docs/_site/showcase/macOSSonomaDesktop.png
./docs/_site/showcase/VManTemplateImport.png
./docs/_site/showcase/OpenCoreSonomaRecoveryInstallation2.png
./docs/_site/showcase/OpenCoreSonomaSecondBootPhase.png
./docs/_site/showcase/macOSSonomaNoMountEFIneeded.png
./docs/_site/showcase/HacProKVM1351.png
./docs/_site/showcase/haxi0DKVM.png
./docs/_site/showcase/VManGPUPassthroughCompletedExample.png
./docs/_site/showcase/HacProKVM141.png
./docs/_site/showcase/Helio1421.png
./docs/_site/showcase/OpenCoreSonomaThirdBootPhase.png
./docs/_site/showcase/kaggsterDKVM135.png
./docs/_site/showcase/ZormDKVMnvidia.png
./docs/_site/showcase/HacProKVM134.png
./docs/_site/assets/HeaderHostPreparations.png
./docs/_site/assets/HeaderDisplayOverrides.png
./docs/_site/assets/Header.png
./docs/_site/assets/HeaderSnowLeopard.png
./docs/_site/assets/OpenCoreSonomaInstallationComplete.png
./docs/_site/assets/HackintoolDisplayView.png
./docs/_site/assets/VManAddBridgeNIC.png
./docs/_site/assets/Header404.png
./docs/_site/assets/macOSRecoveryFormatInstallTarget2.png
./docs/_site/assets/HeaderGST.png
./docs/_site/assets/HeadersPPT.png
./docs/_site/assets/lstopoexample.png
./docs/_site/assets/PTMemRAMFake.png
./docs/_site/assets/DisplayNightLightOff.png
./docs/_site/assets/IOMMUGroupChecker.png
./docs/_site/assets/HeaderVirtualMachine.png
./docs/_site/assets/VManGPUPassthroughRemoveRecoveryKBM.png
./docs/_site/assets/DiskProvisionPostImageMount.png
./docs/_site/assets/macOSSonomaDesktop.png
./docs/_site/assets/HeaderHighSierra.png
./docs/_site/assets/macOSRecoveryDiskUtility.png
./docs/_site/assets/HeaderXMLUsage.png
./docs/_site/assets/DisplaysDefault.png
./docs/_site/assets/VManTemplateImport.png
./docs/_site/assets/OpenCoreBooterQuirks.png
./docs/_site/assets/OpenCoreACPIAdd.png
./docs/_site/assets/OpenCoreRGXExample.png
./docs/_site/assets/HeaderSettingExpectations.png
./docs/_site/assets/OpenCoreSonomaRecoveryInstallation2.png
./docs/_site/assets/HeaderElCapitan.png
./docs/_site/assets/OpenCoreFPAFinished.png
./docs/_site/assets/HeaderBridgeProvision.png
./docs/_site/assets/VManGPUPassthroughCorrectAudioBusBefore.png
./docs/_site/assets/DisplaysIsTVFalse.png
./docs/_site/assets/VManGPUPassthroughCorrectAudioBusAfter.png
./docs/_site/assets/HeaderBigSur.png
./docs/_site/assets/DiskProvisionMountingDiskImage.png
./docs/_site/assets/DarwinKVMLogo.png
./docs/_site/assets/HeaderTiger.png
./docs/_site/assets/HeaderCheetah.png
./docs/_site/assets/DiskProvisionPostImageCreation.png
./docs/_site/assets/HeaderNVMeCompat.png
./docs/_site/assets/VManGPUPassthroughAddNVME.png
./docs/_site/assets/VManDefaultNetworkNIC.png
./docs/_site/assets/VManAddVirtIOInstallation.png
./docs/_site/assets/HeaderLeopard.png
./docs/_site/assets/HeaderCatalina.png
./docs/_site/assets/macOSSonomaGPUAccel.png
./docs/_site/assets/HackintoolOverridesOutput.png
./docs/_site/assets/HeaderOfflineInstaller.png
./docs/_site/assets/PTMemMapLayout.png
./docs/_site/assets/OpenCoreMisc.png
./docs/_site/assets/VManGPUPassthroughAddUSBController2.png
./docs/_site/assets/HeaderFPA.png
./docs/_site/assets/HeaderOCOverview.png
./docs/_site/assets/HeaderVentura.png
./docs/_site/assets/HeaderMavericks.png
./docs/_site/assets/VManGPUPassthroughRemoveVirtIODisplay.png
./docs/_site/assets/OpenCoreUEFI.png
./docs/_site/assets/8Corelstopo.png
./docs/_site/assets/OpenCoreSonomaRecoveryBoot.png
./docs/_site/assets/discord-logo-white.png
./docs/_site/assets/DisplaysProductID2.png
./docs/_site/assets/QEMUHookModification.png
./docs/_site/assets/macrecovery.png
./docs/_site/assets/HackinToolPCIFPA.png
./docs/_site/assets/HeaderMojave.png
./docs/_site/assets/OpenCoreALCBootArg.png
./docs/_site/assets/lstopo-idealvmstart.png
./docs/_site/assets/DisplaysPatched.png
./docs/_site/assets/HeaderMoboAudio.png
./docs/_site/assets/HeaderNetworking.png
./docs/_site/assets/DiskProvisionAddingOCAlternative.png
./docs/_site/assets/HeaderWiFiCompat.png
./docs/_site/assets/DiskProvisionCreatingOCImage.png
./docs/_site/assets/HeaderIOMMU.png
./docs/_site/assets/DisplayNightLightOn.png
./docs/_site/assets/macOSRecoveryFormatInstallTarget3.png
./docs/_site/assets/VManRemoveRecoveryKBM.png
./docs/_site/assets/PTCustomMemoryConfig.png
./docs/_site/assets/OpenCoreSonomaSecondBootPhase.png
./docs/_site/assets/HeaderPanther.png
./docs/_site/assets/HeaderNVMePT.png
./docs/_site/assets/OverridesInstallation.png
./docs/_site/assets/VManFCorePage.png
./docs/_site/assets/HeaderBridgeNetworking.png
./docs/_site/assets/OpenCoreFPARemoveBoot.png
./docs/_site/assets/macOSSonomaNoMountEFIneeded.png
./docs/_site/assets/HeaderConfigs.png
./docs/_site/assets/lstopo-cores.png
./docs/_site/assets/HeaderPackageInstallation.png
./docs/_site/assets/MemoryMappedMacPro71.png
./docs/_site/assets/OpenCoreEFIComplete.png
./docs/_site/assets/HeaderKernelParams.png
./docs/_site/assets/PTMemRAMReal.png
./docs/_site/assets/DisplaysProductID.png
./docs/_site/assets/OverridesHiDPIBefore.png
./docs/_site/assets/VManFPAAttemptReason.png
./docs/_site/assets/OpenCoreDeviceProperties.png
./docs/_site/assets/HeaderCPUPinning.png
./docs/_site/assets/HackintoolIdle.png
./docs/_site/assets/HeaderAboutThisProject.png
./docs/_site/assets/HeaderiGPU.png
./docs/_site/assets/HeaderThreadPinning.png
./docs/_site/assets/BridgeNetworkingLocalTerminal.png
./docs/_site/assets/OpenCoreLocalCreation.png
./docs/_site/assets/DiskProvisionMainMenu.png
./docs/_site/assets/MemoryMapHostMobo.png
./docs/_site/assets/HeaderVirtIOThreads.png
./docs/_site/assets/OverridesHiDPI.png
./docs/_site/assets/HeaderUSBMapping.png
./docs/_site/assets/HeaderSonoma.png
./docs/_site/assets/BridgeNetworkingRouterDash.png
./docs/_site/assets/HeaderFetchingInstaller.png
./docs/_site/assets/HeaderDisplayOverridesTextOnly.png
./docs/_site/assets/VManGPUPassthroughCompletedExample.png
./docs/_site/assets/MemoryMapGuestLayout.png
./docs/_site/assets/VManAddVirtIOInstallation2.png
./docs/_site/assets/VManGPUPassthroughFindGPUBus.png
./docs/_site/assets/HeaderMountainLion.png
./docs/_site/assets/VMMemoryError.png
./docs/_site/assets/PTMemMap32GBDefault.png
./docs/_site/assets/VManAddRecoveryDisplay2.png
./docs/_site/assets/HeaderRequirements.png
./docs/_site/assets/HeaderLion.png
./docs/_site/assets/HeaderSierra.png
./docs/_site/assets/OverridesHiDPIAfter.png
./docs/_site/assets/HeaderInstallingmacOS.png
./docs/_site/assets/HeaderOpenCoreAlt.png
./docs/_site/assets/VManFPABeforeFix.png
./docs/_site/assets/HeaderCongrats.png
./docs/_site/assets/HeaderCascadeLake.png
./docs/_site/assets/HeaderDocsLayout.png
./docs/_site/assets/macOSRecoveryFormatInstallTarget.png
./docs/_site/assets/BaseSystemInstallLegacyScreenshot.png
./docs/_site/assets/VManFPAAttemptError.png
./docs/_site/assets/VManGPUPassthroughAddUSBController1.png
./docs/_site/assets/OverridesHiDPIPT.png
./docs/_site/assets/VManFPAAfterFix.png
./docs/_site/assets/OpenCorePkgBase.png
./docs/_site/assets/HeaderHostOC.png
./docs/_site/assets/VManGPUPassthroughCorrectedGPUMultifunction.png
./docs/_site/assets/OpenCoreSonomaRecoveryInstallation1.png
./docs/_site/assets/HeaderGallery.png
./docs/_site/assets/HeaderRE.png
./docs/_site/assets/HeaderRecoveryInstaller.png
./docs/_site/assets/BridgeNetworkingHypervisorSSH.png
./docs/_site/assets/DisplaysIsTVFalse2.png
./docs/_site/assets/HeaderMonterey.png
./docs/_site/assets/VManAddOpenCore1.png
./docs/_site/assets/OpenCoreProperTree.png
./docs/_site/assets/discord-mark-white.png
./docs/_site/assets/PTgpuargs.png
./docs/_site/assets/VManAddRecoveryDisplay1.png
./docs/_site/assets/VManGPUPassthroughAddMultithreading.png
./docs/_site/assets/HeaderTextOnly.png
./docs/_site/assets/VManGPUPassthroughAddGPU.png
./docs/_site/assets/VManGPUPassthroughAddGPUAudio.png
./docs/_site/assets/OpenCorePlatformInfo.png
./docs/_site/assets/HeaderBTCompat.png
./docs/_site/assets/VManAddOpenCore2.png
./docs/_site/assets/Overrides2Kexample.png
./docs/_site/assets/HeaderOpenCore.png
./docs/_site/assets/HeaderEvdevKBM.png
./docs/_site/assets/HeaderPuma.png
./docs/_site/assets/HWCheckALC.png
./docs/_site/assets/HeaderYosemite.png
./docs/_site/assets/OpenCoreSonomaThirdBootPhase.png
./docs/_site/assets/HeaderDGPU.png
./docs/_site/assets/HeaderGPUCompat.png
./docs/_site/assets/HeaderDiskProvision.png
./docs/_site/assets/OpenCoreUnmount.png
./docs/_site/assets/HWCheckALCReference.png
./docs/_site/assets/HeaderFCC.png
./docs/_site/assets/OpenCoreFPANewDevProp.png
./docs/_site/assets/HeaderGatheringFiles.png
./docs/_site/assets/OpenCoreNVRAM.png
./docs/_site/assets/VManAddFPA.png
./docs/_site/assets/VManFPAAttempt.png
./docs/_site/assets/HeaderBridgeNetworkingTextOnly.png
./docs/_site/assets/HeaderJaguar.png
./docs/_site/assets/HeaderCMM.png
./docs/_site/assets/VManExampleReadyToInstall.png
./docs/_site/assets/OpenCoreVMBootRecovery.png
./docs/_site/assets/6Corelstopo.png
./docs/_site/assets/BootingRecovery.png
./docs/_site/assets/macOSACLID.png
./docs/_site/assets/HeaderSGPU.png
./docs/_site/assets/HeaderBaseSystem.png
./docs/_site/assets/BridgeNetworkingRPI.png
./docs/_site/assets/OpenCoreKernel.png
./docs/_site/assets/PTMemRAMEmptyDIMM.png
./docs/_site/assets/HeaderNVPatch.png
./docs/_site/assets/TerminalHTOP.png
./docs/android-chrome-512x512.png
./docs/showcase/OpenCoreSonomaInstallationComplete.png
./docs/showcase/HacProKVM140.png
./docs/showcase/macOSSonomaDesktop.png
./docs/showcase/VManTemplateImport.png
./docs/showcase/OpenCoreSonomaRecoveryInstallation2.png
./docs/showcase/OpenCoreSonomaSecondBootPhase.png
./docs/showcase/macOSSonomaNoMountEFIneeded.png
./docs/showcase/HacProKVM1351.png
./docs/showcase/haxi0DKVM.png
./docs/showcase/VManGPUPassthroughCompletedExample.png
./docs/showcase/HacProKVM141.png
./docs/showcase/Helio1421.png
./docs/showcase/OpenCoreSonomaThirdBootPhase.png
./docs/showcase/kaggsterDKVM135.png
./docs/showcase/ZormDKVMnvidia.png
./docs/showcase/HacProKVM134.png
./docs/assets/HeaderHostPreparations.png
./docs/assets/HeaderDisplayOverrides.png
./docs/assets/Header.png
./docs/assets/HeaderSnowLeopard.png
./docs/assets/OpenCoreSonomaInstallationComplete.png
./docs/assets/HackintoolDisplayView.png
./docs/assets/VManAddBridgeNIC.png
./docs/assets/Header404.png
./docs/assets/macOSRecoveryFormatInstallTarget2.png
./docs/assets/HeaderGST.png
./docs/assets/HeadersPPT.png
./docs/assets/lstopoexample.png
./docs/assets/PTMemRAMFake.png
./docs/assets/DisplayNightLightOff.png
./docs/assets/IOMMUGroupChecker.png
./docs/assets/HeaderVirtualMachine.png
./docs/assets/VManGPUPassthroughRemoveRecoveryKBM.png
./docs/assets/DiskProvisionPostImageMount.png
./docs/assets/macOSSonomaDesktop.png
./docs/assets/HeaderHighSierra.png
./docs/assets/macOSRecoveryDiskUtility.png
./docs/assets/HeaderXMLUsage.png
./docs/assets/DisplaysDefault.png
./docs/assets/VManTemplateImport.png
./docs/assets/OpenCoreBooterQuirks.png
./docs/assets/OpenCoreACPIAdd.png
./docs/assets/OpenCoreRGXExample.png
./docs/assets/HeaderSettingExpectations.png
./docs/assets/OpenCoreSonomaRecoveryInstallation2.png
./docs/assets/HeaderElCapitan.png
./docs/assets/OpenCoreFPAFinished.png
./docs/assets/HeaderBridgeProvision.png
./docs/assets/VManGPUPassthroughCorrectAudioBusBefore.png
./docs/assets/DisplaysIsTVFalse.png
./docs/assets/VManGPUPassthroughCorrectAudioBusAfter.png
./docs/assets/HeaderBigSur.png
./docs/assets/DiskProvisionMountingDiskImage.png
./docs/assets/DarwinKVMLogo.png
./docs/assets/HeaderTiger.png
./docs/assets/HeaderCheetah.png
./docs/assets/DiskProvisionPostImageCreation.png
./docs/assets/HeaderNVMeCompat.png
./docs/assets/VManGPUPassthroughAddNVME.png
./docs/assets/VManDefaultNetworkNIC.png
./docs/assets/VManAddVirtIOInstallation.png
./docs/assets/HeaderLeopard.png
./docs/assets/HeaderCatalina.png
./docs/assets/macOSSonomaGPUAccel.png
./docs/assets/HackintoolOverridesOutput.png
./docs/assets/HeaderOfflineInstaller.png
./docs/assets/PTMemMapLayout.png
./docs/assets/OpenCoreMisc.png
./docs/assets/VManGPUPassthroughAddUSBController2.png
./docs/assets/HeaderFPA.png
./docs/assets/HeaderOCOverview.png
./docs/assets/HeaderVentura.png
./docs/assets/HeaderMavericks.png
./docs/assets/VManGPUPassthroughRemoveVirtIODisplay.png
./docs/assets/OpenCoreUEFI.png
./docs/assets/8Corelstopo.png
./docs/assets/OpenCoreSonomaRecoveryBoot.png
./docs/assets/discord-logo-white.png
./docs/assets/DisplaysProductID2.png
./docs/assets/QEMUHookModification.png
./docs/assets/macrecovery.png
./docs/assets/HackinToolPCIFPA.png
./docs/assets/HeaderMojave.png
./docs/assets/OpenCoreALCBootArg.png
./docs/assets/lstopo-idealvmstart.png
./docs/assets/DisplaysPatched.png
./docs/assets/HeaderMoboAudio.png
./docs/assets/HeaderNetworking.png
./docs/assets/DiskProvisionAddingOCAlternative.png
./docs/assets/HeaderWiFiCompat.png
./docs/assets/DiskProvisionCreatingOCImage.png
./docs/assets/HeaderIOMMU.png
./docs/assets/DisplayNightLightOn.png
./docs/assets/macOSRecoveryFormatInstallTarget3.png
./docs/assets/VManRemoveRecoveryKBM.png
./docs/assets/PTCustomMemoryConfig.png
./docs/assets/OpenCoreSonomaSecondBootPhase.png
./docs/assets/HeaderPanther.png
./docs/assets/HeaderNVMePT.png
./docs/assets/OverridesInstallation.png
./docs/assets/VManFCorePage.png
./docs/assets/HeaderBridgeNetworking.png
./docs/assets/OpenCoreFPARemoveBoot.png
./docs/assets/macOSSonomaNoMountEFIneeded.png
./docs/assets/HeaderConfigs.png
./docs/assets/lstopo-cores.png
./docs/assets/HeaderPackageInstallation.png
./docs/assets/MemoryMappedMacPro71.png
./docs/assets/OpenCoreEFIComplete.png
./docs/assets/HeaderKernelParams.png
./docs/assets/PTMemRAMReal.png
./docs/assets/DisplaysProductID.png
./docs/assets/OverridesHiDPIBefore.png
./docs/assets/VManFPAAttemptReason.png
./docs/assets/OpenCoreDeviceProperties.png
./docs/assets/HeaderCPUPinning.png
./docs/assets/HackintoolIdle.png
./docs/assets/HeaderAboutThisProject.png
./docs/assets/HeaderiGPU.png
./docs/assets/HeaderThreadPinning.png
./docs/assets/BridgeNetworkingLocalTerminal.png
./docs/assets/OpenCoreLocalCreation.png
./docs/assets/DiskProvisionMainMenu.png
./docs/assets/MemoryMapHostMobo.png
./docs/assets/HeaderVirtIOThreads.png
./docs/assets/OverridesHiDPI.png
./docs/assets/HeaderUSBMapping.png
./docs/assets/HeaderSonoma.png
./docs/assets/BridgeNetworkingRouterDash.png
./docs/assets/HeaderFetchingInstaller.png
./docs/assets/HeaderDisplayOverridesTextOnly.png
./docs/assets/VManGPUPassthroughCompletedExample.png
./docs/assets/MemoryMapGuestLayout.png
./docs/assets/VManAddVirtIOInstallation2.png
./docs/assets/VManGPUPassthroughFindGPUBus.png
./docs/assets/HeaderMountainLion.png
./docs/assets/VMMemoryError.png
./docs/assets/PTMemMap32GBDefault.png
./docs/assets/VManAddRecoveryDisplay2.png
./docs/assets/HeaderRequirements.png
./docs/assets/HeaderLion.png
./docs/assets/HeaderSierra.png
./docs/assets/OverridesHiDPIAfter.png
./docs/assets/HeaderInstallingmacOS.png
./docs/assets/HeaderOpenCoreAlt.png
./docs/assets/VManFPABeforeFix.png
./docs/assets/HeaderCongrats.png
./docs/assets/HeaderCascadeLake.png
./docs/assets/HeaderDocsLayout.png
./docs/assets/macOSRecoveryFormatInstallTarget.png
./docs/assets/BaseSystemInstallLegacyScreenshot.png
./docs/assets/VManFPAAttemptError.png
./docs/assets/VManGPUPassthroughAddUSBController1.png
./docs/assets/OverridesHiDPIPT.png
./docs/assets/VManFPAAfterFix.png
./docs/assets/OpenCorePkgBase.png
./docs/assets/HeaderHostOC.png
./docs/assets/VManGPUPassthroughCorrectedGPUMultifunction.png
./docs/assets/OpenCoreSonomaRecoveryInstallation1.png
./docs/assets/HeaderGallery.png
./docs/assets/HeaderRE.png
./docs/assets/HeaderRecoveryInstaller.png
./docs/assets/BridgeNetworkingHypervisorSSH.png
./docs/assets/DisplaysIsTVFalse2.png
./docs/assets/HeaderMonterey.png
./docs/assets/VManAddOpenCore1.png
./docs/assets/OpenCoreProperTree.png
./docs/assets/discord-mark-white.png
./docs/assets/PTgpuargs.png
./docs/assets/VManAddRecoveryDisplay1.png
./docs/assets/VManGPUPassthroughAddMultithreading.png
./docs/assets/HeaderTextOnly.png
./docs/assets/VManGPUPassthroughAddGPU.png
./docs/assets/VManGPUPassthroughAddGPUAudio.png
./docs/assets/OpenCorePlatformInfo.png
./docs/assets/HeaderBTCompat.png
./docs/assets/VManAddOpenCore2.png
./docs/assets/Overrides2Kexample.png
./docs/assets/HeaderOpenCore.png
./docs/assets/HeaderEvdevKBM.png
./docs/assets/HeaderPuma.png
./docs/assets/HWCheckALC.png
./docs/assets/HeaderYosemite.png
./docs/assets/OpenCoreSonomaThirdBootPhase.png
./docs/assets/HeaderDGPU.png
./docs/assets/HeaderGPUCompat.png
./docs/assets/HeaderDiskProvision.png
./docs/assets/OpenCoreUnmount.png
./docs/assets/HWCheckALCReference.png
./docs/assets/HeaderFCC.png
./docs/assets/OpenCoreFPANewDevProp.png
./docs/assets/HeaderGatheringFiles.png
./docs/assets/OpenCoreNVRAM.png
./docs/assets/VManAddFPA.png
./docs/assets/VManFPAAttempt.png
./docs/assets/HeaderBridgeNetworkingTextOnly.png
./docs/assets/HeaderJaguar.png
./docs/assets/HeaderCMM.png
./docs/assets/VManExampleReadyToInstall.png
./docs/assets/OpenCoreVMBootRecovery.png
./docs/assets/6Corelstopo.png
./docs/assets/BootingRecovery.png
./docs/assets/macOSACLID.png
./docs/assets/HeaderSGPU.png
./docs/assets/HeaderBaseSystem.png
./docs/assets/BridgeNetworkingRPI.png
./docs/assets/OpenCoreKernel.png
./docs/assets/PTMemRAMEmptyDIMM.png
./docs/assets/HeaderNVPatch.png
./docs/assets/TerminalHTOP.png
./DiskProvision/assets/VManAddOC2.png
./DiskProvision/assets/LegacyUnmountExample.png
./DiskProvision/assets/Example.png
./DiskProvision/assets/HeaderDiskProvision.png
./DiskProvision/assets/VManAddOC1.png
./DiskProvision/assets/LegacyExample.png
./Assets/DarwinKVMLogo.png
./Assets/discord-logo-white.png
./Assets/HeaderGallery.png
./Assets/discord-mark-white.png
./Assets/HeaderTextOnly.png
./showcase/OpenCoreSonomaInstallationComplete.png
./showcase/HacProKVM140.png
./showcase/macOSSonomaDesktop.png
./showcase/VManTemplateImport.png
./showcase/OpenCoreSonomaRecoveryInstallation2.png
./showcase/OpenCoreSonomaSecondBootPhase.png
./showcase/macOSSonomaNoMountEFIneeded.png
./showcase/HacProKVM1351.png
./showcase/haxi0DKVM.png
./showcase/VManGPUPassthroughCompletedExample.png
./showcase/HacProKVM141.png
./showcase/Helio1421.png
./showcase/OpenCoreSonomaThirdBootPhase.png
./showcase/kaggsterDKVM135.png
./showcase/ZormDKVMnvidia.png
./showcase/HacProKVM134.png
./macos-display-overrides/resources/Screen Shot 2021-04-10 at 14.47.09.png
</details>

**Comment by royalgraphx** [comment]
Only the ones below docs/assets should be clickable if they're used in a page. Exclude images that begin with ``Header`` as we don't want any of those to be expandable. The goal would be to mainly update screenshots to be expandable.
