### ISSUE TITLE
Evdev

### ISSUE THREAD

**Issue by rolowilde** [royalgraphx/DarwinKVM#3]
Could make a section in 03-VManUpdate.md for those who are unable to passthrough usb controller to vm to at least get keyboard and mouse working via [evdev](https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF#Passing_keyboard/mouse_via_Evdev).

**Comment by royalgraphx** [comment]
Blank KBM Via Evdev write up section has gone live, feel free to make a PR. 🙏🏻

**Comment by royalgraphx** [comment]
reopening as GPU-less Users will eventually be taken account of, and this can be useful for quick swapping

**Comment by royalgraphx** [comment]
completed with PR #13
